### ISSUE TITLE
"Collision" Frame

### ISSUE THREAD

**Issue by marcosb1** [Capping-CPCA/Attendance-App#14]
In case we find two or more participants that have the same name we need to trigger a user action

**Comment by sami10015** [comment]
@marcosb1 I wanted to know on any updates regarding this bug. There is a UI piece to this, as well as a DB piece. From my understanding, the DB piece needs to be done before working on the UI, or we won't be able to see whether it is functional or not. Will we be able to deploy this by Friday? Also, how big of a deal is this issue? In other words, is this something you see causing major issues in the future, or something that can be backlogged?

**Comment by marcosb1** [comment]
@sami10015 I am actively working on this. The UI piece comes before AND after the DB part because I don't have windowbuilder, so Carlie made the frame layout and once I place the logic in the `UploadFrame` we need to go back to the window builder portion of this. 

This is not a HUGE concern since they are not that likely to get the same name for a person twice. But it should be something that we wrap-up before the semester ends.
