### ISSUE TITLE
App Styling

### ISSUE THREAD

**Issue by marcosb1** [Capping-CPCA/Attendance-App#18]
Maybe work on styling now that the functionality is pretty much all done.

**Comment by Scott123180** [comment]
Some oracle references that might be helpful in customizing swing:
https://docs.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

If you really wanted to go the extra 2 miles, you can transition to JavaFX to get  a GUI that looks just as good or better than the web app. That would probably be a long undertaking though. Here's a useful link for transitioning from Swing to JavaFX:
http://www.dreamincode.net/forums/topic/339799-swing-to-javafx/
