### ISSUE TITLE
Window Sizing

### ISSUE THREAD

**Issue by Scott123180** [Capping-CPCA/Attendance-App#22]
Was testing the app on my machine and found some window sizing issues. Was not able to resize the attendance window and class information window.

Granted they're not going to be running 4k monitors, but they might be in the next 5 years.

![screenshot from 2017-11-15 21-54-09](https://user-images.githubusercontent.com/9338669/32871563-ce4fbfec-ca4f-11e7-97ae-79b63ed80a68.png)

**Comment by sami10015** [comment]
Resizing is actually a much harder task than you would think. Unfortunately, we kinda messed ourselves up with using the Window Builder instead of a specific Java Swing Layout, so this is just going to have to stay the way it is.
