### ISSUE TITLE
Updating 'chached' fields for offline use automatically

### ISSUE THREAD

**Issue by marcosb1** [Capping-CPCA/Attendance-App#26]
Since we store the dropdown fields and other pre-populated information in `.properties` files, we need to be sure to update these fields when they re-connect to the network so that they may have the most current information on their system.

**Comment by sami10015** [comment]
Is this a simple fix, or is it more complicated than that? You created the DB manager, so I feel as if you would know best.

**Comment by marcosb1** [comment]
Already fixed it I think, just haven't had the chance to test it with the collision frame @sami10015
